package hu.squarelabs.auth21.service;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import hu.squarelabs.auth21.exception.UserAlreadyExistsException;
import hu.squarelabs.auth21.model.entity.UserEntity;
import hu.squarelabs.auth21.repository.UserRepository;
import java.util.Optional;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

@DisplayName("UserService")
@ExtendWith(MockitoExtension.class)
class UserServiceTest {
  @Mock private PasswordEncoder passwordEncoder;
  @Mock private UserRepository userRepository;
  @InjectMocks private UserService userService;

  @Nested
  @DisplayName("create")
  class Create {
    @Test
    @DisplayName("creates new user with encoded password and auto-generated ID")
    void createsNewUserWithEncodedPasswordAndAutoGeneratedId() {
      when(userRepository.findByUsernameOrEmail("test@example.com", "testuser"))
          .thenReturn(Optional.empty());
      when(passwordEncoder.encode("password123")).thenReturn("hashedPassword");
      doNothing().when(userRepository).save(any(UserEntity.class));

      String userId =
          userService.create("test@example.com", "password123", "testuser", "Test User");

      ArgumentCaptor<UserEntity> userCaptor = ArgumentCaptor.forClass(UserEntity.class);
      verify(userRepository).save(userCaptor.capture());
      UserEntity savedUser = userCaptor.getValue();
      assertThat(userId).isNotBlank();
      assertThat(savedUser.getEmail()).isEqualTo("test@example.com");
      assertThat(savedUser.getUsername()).isEqualTo("testuser");
      assertThat(savedUser.getDisplayName()).isEqualTo("Test User");
      assertThat(savedUser.getPassword()).isEqualTo("hashedPassword");
      assertThat(savedUser.getId()).isNotNull();
    }

    @Test
    @DisplayName("throws UserAlreadyExistsException when user already exists")
    void throwsUserAlreadyExistsExceptionWhenUserAlreadyExists() {
      UserEntity existingUser = new UserEntity();
      existingUser.setId("existing-123");
      existingUser.setEmail("existing@example.com");
      existingUser.setUsername("existinguser");
      when(userRepository.findByUsernameOrEmail("existing@example.com", "existinguser"))
          .thenReturn(Optional.of(existingUser));

      assertThatThrownBy(
              () ->
                  userService.create(
                      "existing@example.com", "password123", "existinguser", "Existing User"))
          .isInstanceOf(UserAlreadyExistsException.class);

      verify(userRepository, never()).save(any(UserEntity.class));
    }
  }

  @Nested
  @DisplayName("getUserByEmail")
  class GetUserByEmail {
    @Test
    @DisplayName("returns user when found")
    void returnsUserWhenFound() {
      final String email = "test@example.com";
      UserEntity user = new UserEntity();
      user.setId("user-123");
      user.setEmail(email);
      when(userRepository.findByEmail(email)).thenReturn(Optional.of(user));
      Optional<UserEntity> result = userService.getUserByEmail(email);
      assertThat(result).isPresent();
      assertThat(result.get().getEmail()).isEqualTo(email);
      verify(userRepository).findByEmail(email);
    }

    @Test
    @DisplayName("should return empty when user not found")
    void shouldReturnEmptyWhenNotFound() {
      when(userRepository.findByEmail("nonexistent@example.com")).thenReturn(Optional.empty());

      Optional<UserEntity> result = userService.getUserByEmail("nonexistent@example.com");

      assertThat(result).isEmpty();
      verify(userRepository).findByEmail("nonexistent@example.com");
    }
  }

  @Nested
  @DisplayName("getUserById")
  class GetUserById {
    @Test
    @DisplayName("returns user when found")
    void returnsUserWhenFound() {
      final String userId = "user-123";
      UserEntity user = new UserEntity();
      user.setId(userId);
      user.setEmail("test@example.com");
      when(userRepository.findById(userId)).thenReturn(Optional.of(user));
      Optional<UserEntity> result = userService.getUserById(userId);
      assertThat(result).isPresent();
      assertThat(result.get().getId()).isEqualTo(userId);
      verify(userRepository).findById(userId);
    }

    @Test
    @DisplayName("should return empty when user not found")
    void shouldReturnEmptyWhenNotFound() {
      when(userRepository.findById("nonexistent-123")).thenReturn(Optional.empty());

      Optional<UserEntity> result = userService.getUserById("nonexistent-123");

      assertThat(result).isEmpty();
      verify(userRepository).findById("nonexistent-123");
    }
  }

  @Nested
  @DisplayName("getUserByUserName")
  class GetUserByUserName {
    @Test
    @DisplayName("returns user when found")
    void returnsUserWhenFound() {
      final String username = "testuser";
      UserEntity user = new UserEntity();
      user.setId("user-123");
      user.setUsername(username);
      when(userRepository.findByUserName(username)).thenReturn(Optional.of(user));
      Optional<UserEntity> result = userService.getUserByUserName(username);
      assertThat(result).isPresent();
      assertThat(result.get().getUsername()).isEqualTo(username);
      verify(userRepository).findByUserName(username);
    }

    @Test
    @DisplayName("returns empty when not found")
    void returnsEmptyWhenNotFound() {
      when(userRepository.findByUserName("nonexistent")).thenReturn(Optional.empty());

      Optional<UserEntity> result = userService.getUserByUserName("nonexistent");

      assertThat(result).isEmpty();
      verify(userRepository).findByUserName("nonexistent");
    }
  }
}
